### ISSUE TITLE
Can't build the zk library with latest elliptic changes

### ISSUE THREAD

**Issue by jdhollis** [NuID/elliptic#1]
@Nolan330 Looks like you left a local dependency in place: https://github.com/NuID/elliptic/blob/02ae5cdede5cef6798cae01cd773dee015dd1bf0/deps.edn#L8

This is blocking me from building a version of the library for use in the Rails app.

**Comment by usernolan** [comment]
Bah! Apologies, will fix shortly.

**Comment by jdhollis** [comment]
Thank you kindly.

**Comment by usernolan** [comment]
Should be fixed in https://github.com/NuID/elliptic/commit/5a53da3a097384da98db77e56be821f16e65d842. Will be testing functionality and usage from JS as I go through packaging these up for `npm`. It will be good to have you working with it to get some feedback on where the sharp edges are.

**Comment by jdhollis** [comment]
I’ve gotten it to build successfully now. I’ll let you know tomorrow how it plays in the browser.
